### PR TITLE
updates for wq 1.0 beta 2; leverage outbox FKs

### PR DESCRIPTION
**Pull request by sheppard**
wq 1.0 beta 2 allows foreign keys to be used to reference items that are still in the outbox.  I enabled this feature for the observation model so you can now create multiple repeat observations while offline.  In theory, we should be able to use the same principle for sites (including polygon sites) but I haven't updated it to do this yet.

Other updates include:
 - Latest versions of wq, Django, etc.
 - Tested on Ubuntu 16.04 LTS
 - Use a venv (Python 3's built in virtualenv)

To test this before merging it, follow the [updated instructions](https://github.com/powered-by-wq/atlasbiowork.com/tree/outbox-update) but replace the following step:
```bash
git clone https://github.com/Soil-Carbon-Coalition/atlasbiowork .
```
with this:
```bash
git clone https://github.com/powered-by-wq/atlasbiowork.com.git .
git checkout -b outbox-update origin/outbox-update
```

Also, there is currently a bug in app/js/lib/json-forms.js, so comment out this part before building:

```javascript
function setValue(context, step, currentValue, entryValue, isFile) {
  /*
  if (isFile) {
    entryValue = {
      name: 'filename',
      type: 'filetype',
      body: 'filebody'
    }
  }
  */
  if (step.last) {
```

### CODE REVIEW

**Comment by managingwholes** [comment]
Hi Andrew

Finally getting around to the 16.04. When I tried the second part of step
13, 'git checkout outbox-update', got an error (not a repo). I wasn't too
sure how to run that command, or which url to include.

Then I ran into errors with ./manage.py migrate. Missing social-auth module
which I installed with pip, then psycopg2 which I tried to add and got
several errors. I see these are both in the requirements.txt so something
misfired here.

thanks for any help

**Comment by sheppard** [comment]
Looks like I missed a `.` in my instructions:
```bash
git clone https://github.com/powered-by-wq/atlasbiowork.com.git
git checkout outbox-update
```
should be:
```bash
git clone https://github.com/powered-by-wq/atlasbiowork.com.git .
git checkout outbox-update
```
The idea with the `.` is that you want to clone the repository to the current directory, rather than create a new directory (which is the default action).  I updated the original post to reflect this.

The requirements.txt in the outbox-update branch has social-auth and psycopg2 listed, so if you didn't get those, you are probably using the requirements.txt from the master branch.

**Comment by managingwholes** [comment]
Yes, I figured out the missing period but is the git checkout outbox-update
part of the same bash command or is it a separate one? I could not tell
from the email or the file. thx

**Comment by sheppard** [comment]
Each line starting with `git` is a new bash command.  It looks like I also missed a few arguments to the checkout command.  It should be this:

```bash
git checkout -b outbox-update origin/outbox-update
```

This says to create and checkout a new local branch, "outbox-update", that tracks the outbox-update branch on the remote origin.

**Comment by sheppard** [comment]
You can always check the list of local branches (and see which one you currently have checked out) by typing `git branch`.  After doing the above, you should see this result:

```bash
$ git branch
  master
* outbox-update
```

**Comment by managingwholes** [comment]
Thanks, the git checkout worked well.

I deleted the atlasbiowork directory and redid steps 8 on from the readme,
some of which I got through yesterday.

Here's the output. Two basic errors, one after installing requirements.txt,
the other after ./manage.py migrate


pdonovan@atlas16:/var/www/atlasbiowork$ . venv/bin/activate
-bash: venv/bin/activate: No such file or directory
pdonovan@atlas16:/var/www/atlasbiowork$ python3 -m venv venv
pdonovan@atlas16:/var/www/atlasbiowork$ . venv/bin/activate

(venv) pdonovan@atlas16:/var/www/atlasbiowork$ pip install -r
requirements.txt
Collecting
https://github.com/sheppard/django-media-thumbnailer/archive/master.zip
(from -r requirements.txt (line 7))
  Downloading
https://github.com/sheppard/django-media-thumbnailer/archive/master.zip
     - 10kB 21.5MB/s
Collecting click==5.1 (from -r requirements.txt (line 1))
  Using cached click-5.1-py2.py3-none-any.whl
Collecting compass-stylesheets==0.12.6 (from -r requirements.txt (line 2))
  Using cached compass-stylesheets-0.12.6.tar.gz
Collecting defusedxml==0.4.1 (from -r requirements.txt (line 3))
  Using cached defusedxml-0.4.1.tar.gz
Collecting Django==1.10.3 (from -r requirements.txt (line 4))
  Downloading Django-1.10.3-py2.py3-none-any.whl (6.8MB)
    100% |████████████████████████████████| 6.8MB 164kB/s
Collecting django-mustache==1.1.0 (from -r requirements.txt (line 5))
  Downloading django-mustache-1.1.0.tar.gz
Collecting djangorestframework==3.5.3 (from -r requirements.txt (line 6))
  Downloading djangorestframework-3.5.3-py2.py3-none-any.whl (709kB)
    100% |████████████████████████████████| 716kB 1.3MB/s
Collecting FormEncode==2.0.0a1 (from -r requirements.txt (line 8))
  Downloading FormEncode-2.0.0a1-py2.py3-none-any.whl (351kB)
    100% |████████████████████████████████| 358kB 3.2MB/s
Collecting html-json-forms==1.0.0 (from -r requirements.txt (line 9))
  Downloading html-json-forms-1.0.0.tar.gz
Collecting linecache2==1.0.0 (from -r requirements.txt (line 10))
  Downloading linecache2-1.0.0-py2.py3-none-any.whl
Collecting Markdown==2.6.7 (from -r requirements.txt (line 11))
  Downloading Markdown-2.6.7.zip (413kB)
    100% |████████████████████████████████| 419kB 2.6MB/s
Collecting natural-keys==1.1.0 (from -r requirements.txt (line 12))
  Downloading natural-keys-1.1.0.tar.gz
Collecting oauthlib==2.0.1 (from -r requirements.txt (line 13))
  Using cached oauthlib-2.0.1.tar.gz
Collecting Pillow==3.4.2 (from -r requirements.txt (line 14))
  Using cached Pillow-3.4.2-cp35-cp35m-manylinux1_x86_64.whl
Requirement already satisfied (use --upgrade to upgrade):
pkg-resources==0.0.0 in ./venv/lib/python3.5/site-packages (fr
om -r requirements.txt (line 15))
Collecting psycopg2==2.6.2 (from -r requirements.txt (line 16))
  Using cached psycopg2-2.6.2.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/psycopg2.egg-info
    writing dependency_links to
pip-egg-info/psycopg2.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt
    writing pip-egg-info/psycopg2.egg-info/PKG-INFO
    writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found

    Error: b'You need to install postgresql-server-dev-X.Y for building a
server-side extension or libpq-dev for building a client-side
application.\n'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in
/tmp/pip-build-_blyq254/psycopg2/
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(venv) pdonovan@atlas16:/var/www/atlasbiowork$ cd db/atlasbiowork
(venv) pdonovan@atlas16:/var/www/atlasbiowork/db/atlasbiowork$ cp
local_settings.py.template local_settings.py
(venv) pdonovan@atlas16:/var/www/atlasbiowork/db/atlasbiowork$ vim
local_settings.py
(venv) pdonovan@atlas16:/var/www/atlasbiowork/db/atlasbiowork$ sudo vim
/etc/postgresql/9.5/main/pg_hba.conf
[sudo] password for pdonovan:
(venv) pdonovan@atlas16:/var/www/atlasbiowork/db/atlasbiowork$ sudo service
postgresql restart
(venv) pdonovan@atlas16:/var/www/atlasbiowork/db/atlasbiowork$ createuser
-Upostgres atlasbiowork
createuser: creation of new role failed: ERROR:  role "atlasbiowork"
already exists

(venv) pdonovan@atlas16:/var/www/atlasbiowork/db/atlasbiowork$ psql
-Upostgres atlasbiowork -c "create extension postgis
"
ERROR:  extension "postgis" already exists
(venv) pdonovan@atlas16:/var/www/atlasbiowork/db/atlasbiowork$ cd ..
(venv) pdonovan@atlas16:/var/www/atlasbiowork/db$ ./manage.py migrate
Traceback (most recent call last):
  File "./manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named 'django'
(venv) pdonovan@atlas16:/var/www/atlasbiowork/db$

**Comment by sheppard** [comment]
Try this:
```
sudo apt-get install build-essential libpq-dev python3-dev
```
I'll add this to the instructions as well.  Not having to build psycopg2 from source was one of the benefits of using system-wide python packages - but I think the benefits of using a venv are still worth it.

**Comment by managingwholes** [comment]
Great. ./manage.py migrate worked. I'll try the build tonight or tomorrow.

Two quick questions.

1. The venv is for installing or updating python packages, right? Otherwise
I don't need to activate it?

2. My SSL certificate is only for the atlasbiowork.com domain. I'd like to
test the new installation (it's on a different droplet) before I move data
and DNS -- will my SSL configurations work on the IP address? (Perhaps I
should get one that covers more than one domain.) I'm still pretty hazy on
SSL.

PS
Got errors when running pip install -r requirements.txt on all the wq
modules, e.g.

Failed building wheel for wq.core
  Running setup.py clean for wq.core
  Running setup.py bdist_wheel for wq.db ... error
  Complete output from command /var/www/atlasbiowork/venv/bin/python3 -u -c
"import setuptools, tokenize;__file__='/tmp/
pip-build-u_n09pdq/wq.db/setup.py';exec(compile(getattr(tokenize, 'open',
open)(__file__).read().replace('\r\n', '\n'),
__file__, 'exec'))" bdist_wheel -d /tmp/tmposnn2adgpip-wheel- --python-tag
cp35:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help

  error: invalid command 'bdist_wheel'

**Comment by sheppard** [comment]
The venv is for installing packages as well as anything that requires `manage.py` (e.g. makemigrations).  The WSGI server is able to pick up the venv already thanks to the [`python-home` directive](https://github.com/powered-by-wq/atlasbiowork.com/blob/outbox-update/conf/atlasbiowork.conf#L49).

For the SSL certificate, you can always point it temporarily at the dummy certificate and tell your browser to ignore the error:
```apache
    SSLCertificateFile /etc/ssl/certs/ssl-cert-snakeoil.pem
    SSLCertificateKeyFile /etc/ssl/private/ssl-cert-snakeoil.key
```
Otherwise, you can set up a new DNS host and follow the letsencrypt instructions at the end of https://wq.io/docs/setup-ubuntu to get a certificate dedicated to that host.

The bdist_wheel errors can be ignored, or you can get rid of them by upgrading pip.
```bash
pip install --upgrade pip
```

**Pull request merged**
